#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assign5_ConnectToSqlDB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MCO_368_Asgn5")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCUSTOMER(CUSTOMER instance);
    partial void UpdateCUSTOMER(CUSTOMER instance);
    partial void DeleteCUSTOMER(CUSTOMER instance);
    partial void InsertEMP(EMP instance);
    partial void UpdateEMP(EMP instance);
    partial void DeleteEMP(EMP instance);
    partial void InsertEMPLOYEE(EMPLOYEE instance);
    partial void UpdateEMPLOYEE(EMPLOYEE instance);
    partial void DeleteEMPLOYEE(EMPLOYEE instance);
    partial void InsertINVOICE(INVOICE instance);
    partial void UpdateINVOICE(INVOICE instance);
    partial void DeleteINVOICE(INVOICE instance);
    partial void InsertLINE(LINE instance);
    partial void UpdateLINE(LINE instance);
    partial void DeleteLINE(LINE instance);
    partial void InsertP(P instance);
    partial void UpdateP(P instance);
    partial void DeleteP(P instance);
    partial void InsertPRODUCT(PRODUCT instance);
    partial void UpdatePRODUCT(PRODUCT instance);
    partial void DeletePRODUCT(PRODUCT instance);
    partial void InsertV(V instance);
    partial void UpdateV(V instance);
    partial void DeleteV(V instance);
    partial void InsertVENDOR(VENDOR instance);
    partial void UpdateVENDOR(VENDOR instance);
    partial void DeleteVENDOR(VENDOR instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Assign5_ConnectToSqlDB.Properties.Settings.Default.MCO_368_Asgn5ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CUSTOMER> CUSTOMERs
		{
			get
			{
				return this.GetTable<CUSTOMER>();
			}
		}
		
		public System.Data.Linq.Table<EMP> EMPs
		{
			get
			{
				return this.GetTable<EMP>();
			}
		}
		
		public System.Data.Linq.Table<EMPLOYEE> EMPLOYEEs
		{
			get
			{
				return this.GetTable<EMPLOYEE>();
			}
		}
		
		public System.Data.Linq.Table<INVOICE> INVOICEs
		{
			get
			{
				return this.GetTable<INVOICE>();
			}
		}
		
		public System.Data.Linq.Table<LINE> LINEs
		{
			get
			{
				return this.GetTable<LINE>();
			}
		}
		
		public System.Data.Linq.Table<P> Ps
		{
			get
			{
				return this.GetTable<P>();
			}
		}
		
		public System.Data.Linq.Table<PRODUCT> PRODUCTs
		{
			get
			{
				return this.GetTable<PRODUCT>();
			}
		}
		
		public System.Data.Linq.Table<V> Vs
		{
			get
			{
				return this.GetTable<V>();
			}
		}
		
		public System.Data.Linq.Table<VENDOR> VENDORs
		{
			get
			{
				return this.GetTable<VENDOR>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CUSTOMER")]
	public partial class CUSTOMER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _CUS_CODE;
		
		private string _CUS_LNAME;
		
		private string _CUS_FNAME;
		
		private System.Nullable<char> _CUS_INITIAL;
		
		private string _CUS_AREACODE;
		
		private string _CUS_PHONE;
		
		private System.Nullable<decimal> _CUS_BALANCE;
		
		private EntitySet<INVOICE> _INVOICEs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCUS_CODEChanging(decimal value);
    partial void OnCUS_CODEChanged();
    partial void OnCUS_LNAMEChanging(string value);
    partial void OnCUS_LNAMEChanged();
    partial void OnCUS_FNAMEChanging(string value);
    partial void OnCUS_FNAMEChanged();
    partial void OnCUS_INITIALChanging(System.Nullable<char> value);
    partial void OnCUS_INITIALChanged();
    partial void OnCUS_AREACODEChanging(string value);
    partial void OnCUS_AREACODEChanged();
    partial void OnCUS_PHONEChanging(string value);
    partial void OnCUS_PHONEChanged();
    partial void OnCUS_BALANCEChanging(System.Nullable<decimal> value);
    partial void OnCUS_BALANCEChanged();
    #endregion
		
		public CUSTOMER()
		{
			this._INVOICEs = new EntitySet<INVOICE>(new Action<INVOICE>(this.attach_INVOICEs), new Action<INVOICE>(this.detach_INVOICEs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUS_CODE", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal CUS_CODE
		{
			get
			{
				return this._CUS_CODE;
			}
			set
			{
				if ((this._CUS_CODE != value))
				{
					this.OnCUS_CODEChanging(value);
					this.SendPropertyChanging();
					this._CUS_CODE = value;
					this.SendPropertyChanged("CUS_CODE");
					this.OnCUS_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUS_LNAME", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string CUS_LNAME
		{
			get
			{
				return this._CUS_LNAME;
			}
			set
			{
				if ((this._CUS_LNAME != value))
				{
					this.OnCUS_LNAMEChanging(value);
					this.SendPropertyChanging();
					this._CUS_LNAME = value;
					this.SendPropertyChanged("CUS_LNAME");
					this.OnCUS_LNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUS_FNAME", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string CUS_FNAME
		{
			get
			{
				return this._CUS_FNAME;
			}
			set
			{
				if ((this._CUS_FNAME != value))
				{
					this.OnCUS_FNAMEChanging(value);
					this.SendPropertyChanging();
					this._CUS_FNAME = value;
					this.SendPropertyChanged("CUS_FNAME");
					this.OnCUS_FNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUS_INITIAL", DbType="Char(1)")]
		public System.Nullable<char> CUS_INITIAL
		{
			get
			{
				return this._CUS_INITIAL;
			}
			set
			{
				if ((this._CUS_INITIAL != value))
				{
					this.OnCUS_INITIALChanging(value);
					this.SendPropertyChanging();
					this._CUS_INITIAL = value;
					this.SendPropertyChanged("CUS_INITIAL");
					this.OnCUS_INITIALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUS_AREACODE", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string CUS_AREACODE
		{
			get
			{
				return this._CUS_AREACODE;
			}
			set
			{
				if ((this._CUS_AREACODE != value))
				{
					this.OnCUS_AREACODEChanging(value);
					this.SendPropertyChanging();
					this._CUS_AREACODE = value;
					this.SendPropertyChanged("CUS_AREACODE");
					this.OnCUS_AREACODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUS_PHONE", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string CUS_PHONE
		{
			get
			{
				return this._CUS_PHONE;
			}
			set
			{
				if ((this._CUS_PHONE != value))
				{
					this.OnCUS_PHONEChanging(value);
					this.SendPropertyChanging();
					this._CUS_PHONE = value;
					this.SendPropertyChanged("CUS_PHONE");
					this.OnCUS_PHONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUS_BALANCE", DbType="Decimal(9,2)")]
		public System.Nullable<decimal> CUS_BALANCE
		{
			get
			{
				return this._CUS_BALANCE;
			}
			set
			{
				if ((this._CUS_BALANCE != value))
				{
					this.OnCUS_BALANCEChanging(value);
					this.SendPropertyChanging();
					this._CUS_BALANCE = value;
					this.SendPropertyChanged("CUS_BALANCE");
					this.OnCUS_BALANCEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CUSTOMER_INVOICE", Storage="_INVOICEs", ThisKey="CUS_CODE", OtherKey="CUS_CODE")]
		public EntitySet<INVOICE> INVOICEs
		{
			get
			{
				return this._INVOICEs;
			}
			set
			{
				this._INVOICEs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_INVOICEs(INVOICE entity)
		{
			this.SendPropertyChanging();
			entity.CUSTOMER = this;
		}
		
		private void detach_INVOICEs(INVOICE entity)
		{
			this.SendPropertyChanging();
			entity.CUSTOMER = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EMP")]
	public partial class EMP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _EMP_NUM;
		
		private string _EMP_TITLE;
		
		private string _EMP_LNAME;
		
		private string _EMP_FNAME;
		
		private System.Nullable<char> _EMP_INITIAL;
		
		private System.Nullable<System.DateTime> _EMP_DOB;
		
		private System.Nullable<System.DateTime> _EMP_HIRE_DATE;
		
		private string _EMP_AREACODE;
		
		private string _EMP_PHONE;
		
		private System.Nullable<decimal> _EMP_MGR;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEMP_NUMChanging(decimal value);
    partial void OnEMP_NUMChanged();
    partial void OnEMP_TITLEChanging(string value);
    partial void OnEMP_TITLEChanged();
    partial void OnEMP_LNAMEChanging(string value);
    partial void OnEMP_LNAMEChanged();
    partial void OnEMP_FNAMEChanging(string value);
    partial void OnEMP_FNAMEChanged();
    partial void OnEMP_INITIALChanging(System.Nullable<char> value);
    partial void OnEMP_INITIALChanged();
    partial void OnEMP_DOBChanging(System.Nullable<System.DateTime> value);
    partial void OnEMP_DOBChanged();
    partial void OnEMP_HIRE_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnEMP_HIRE_DATEChanged();
    partial void OnEMP_AREACODEChanging(string value);
    partial void OnEMP_AREACODEChanged();
    partial void OnEMP_PHONEChanging(string value);
    partial void OnEMP_PHONEChanged();
    partial void OnEMP_MGRChanging(System.Nullable<decimal> value);
    partial void OnEMP_MGRChanged();
    #endregion
		
		public EMP()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_NUM", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal EMP_NUM
		{
			get
			{
				return this._EMP_NUM;
			}
			set
			{
				if ((this._EMP_NUM != value))
				{
					this.OnEMP_NUMChanging(value);
					this.SendPropertyChanging();
					this._EMP_NUM = value;
					this.SendPropertyChanged("EMP_NUM");
					this.OnEMP_NUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_TITLE", DbType="Char(10)")]
		public string EMP_TITLE
		{
			get
			{
				return this._EMP_TITLE;
			}
			set
			{
				if ((this._EMP_TITLE != value))
				{
					this.OnEMP_TITLEChanging(value);
					this.SendPropertyChanging();
					this._EMP_TITLE = value;
					this.SendPropertyChanged("EMP_TITLE");
					this.OnEMP_TITLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_LNAME", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string EMP_LNAME
		{
			get
			{
				return this._EMP_LNAME;
			}
			set
			{
				if ((this._EMP_LNAME != value))
				{
					this.OnEMP_LNAMEChanging(value);
					this.SendPropertyChanging();
					this._EMP_LNAME = value;
					this.SendPropertyChanged("EMP_LNAME");
					this.OnEMP_LNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_FNAME", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string EMP_FNAME
		{
			get
			{
				return this._EMP_FNAME;
			}
			set
			{
				if ((this._EMP_FNAME != value))
				{
					this.OnEMP_FNAMEChanging(value);
					this.SendPropertyChanging();
					this._EMP_FNAME = value;
					this.SendPropertyChanged("EMP_FNAME");
					this.OnEMP_FNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_INITIAL", DbType="Char(1)")]
		public System.Nullable<char> EMP_INITIAL
		{
			get
			{
				return this._EMP_INITIAL;
			}
			set
			{
				if ((this._EMP_INITIAL != value))
				{
					this.OnEMP_INITIALChanging(value);
					this.SendPropertyChanging();
					this._EMP_INITIAL = value;
					this.SendPropertyChanged("EMP_INITIAL");
					this.OnEMP_INITIALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_DOB", DbType="Date")]
		public System.Nullable<System.DateTime> EMP_DOB
		{
			get
			{
				return this._EMP_DOB;
			}
			set
			{
				if ((this._EMP_DOB != value))
				{
					this.OnEMP_DOBChanging(value);
					this.SendPropertyChanging();
					this._EMP_DOB = value;
					this.SendPropertyChanged("EMP_DOB");
					this.OnEMP_DOBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_HIRE_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> EMP_HIRE_DATE
		{
			get
			{
				return this._EMP_HIRE_DATE;
			}
			set
			{
				if ((this._EMP_HIRE_DATE != value))
				{
					this.OnEMP_HIRE_DATEChanging(value);
					this.SendPropertyChanging();
					this._EMP_HIRE_DATE = value;
					this.SendPropertyChanged("EMP_HIRE_DATE");
					this.OnEMP_HIRE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_AREACODE", DbType="Char(3)")]
		public string EMP_AREACODE
		{
			get
			{
				return this._EMP_AREACODE;
			}
			set
			{
				if ((this._EMP_AREACODE != value))
				{
					this.OnEMP_AREACODEChanging(value);
					this.SendPropertyChanging();
					this._EMP_AREACODE = value;
					this.SendPropertyChanged("EMP_AREACODE");
					this.OnEMP_AREACODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_PHONE", DbType="Char(8)")]
		public string EMP_PHONE
		{
			get
			{
				return this._EMP_PHONE;
			}
			set
			{
				if ((this._EMP_PHONE != value))
				{
					this.OnEMP_PHONEChanging(value);
					this.SendPropertyChanging();
					this._EMP_PHONE = value;
					this.SendPropertyChanged("EMP_PHONE");
					this.OnEMP_PHONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_MGR", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> EMP_MGR
		{
			get
			{
				return this._EMP_MGR;
			}
			set
			{
				if ((this._EMP_MGR != value))
				{
					this.OnEMP_MGRChanging(value);
					this.SendPropertyChanging();
					this._EMP_MGR = value;
					this.SendPropertyChanged("EMP_MGR");
					this.OnEMP_MGRChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EMPLOYEE")]
	public partial class EMPLOYEE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _EMP_NUM;
		
		private string _EMP_TITLE;
		
		private string _EMP_LNAME;
		
		private string _EMP_FNAME;
		
		private System.Nullable<char> _EMP_INITIAL;
		
		private System.Nullable<System.DateTime> _EMP_DOB;
		
		private System.Nullable<System.DateTime> _EMP_HIRE_DATE;
		
		private System.Nullable<decimal> _EMP_YEARS;
		
		private string _EMP_AREACODE;
		
		private string _EMP_PHONE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEMP_NUMChanging(decimal value);
    partial void OnEMP_NUMChanged();
    partial void OnEMP_TITLEChanging(string value);
    partial void OnEMP_TITLEChanged();
    partial void OnEMP_LNAMEChanging(string value);
    partial void OnEMP_LNAMEChanged();
    partial void OnEMP_FNAMEChanging(string value);
    partial void OnEMP_FNAMEChanged();
    partial void OnEMP_INITIALChanging(System.Nullable<char> value);
    partial void OnEMP_INITIALChanged();
    partial void OnEMP_DOBChanging(System.Nullable<System.DateTime> value);
    partial void OnEMP_DOBChanged();
    partial void OnEMP_HIRE_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnEMP_HIRE_DATEChanged();
    partial void OnEMP_YEARSChanging(System.Nullable<decimal> value);
    partial void OnEMP_YEARSChanged();
    partial void OnEMP_AREACODEChanging(string value);
    partial void OnEMP_AREACODEChanged();
    partial void OnEMP_PHONEChanging(string value);
    partial void OnEMP_PHONEChanged();
    #endregion
		
		public EMPLOYEE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_NUM", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal EMP_NUM
		{
			get
			{
				return this._EMP_NUM;
			}
			set
			{
				if ((this._EMP_NUM != value))
				{
					this.OnEMP_NUMChanging(value);
					this.SendPropertyChanging();
					this._EMP_NUM = value;
					this.SendPropertyChanged("EMP_NUM");
					this.OnEMP_NUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_TITLE", DbType="Char(10)")]
		public string EMP_TITLE
		{
			get
			{
				return this._EMP_TITLE;
			}
			set
			{
				if ((this._EMP_TITLE != value))
				{
					this.OnEMP_TITLEChanging(value);
					this.SendPropertyChanging();
					this._EMP_TITLE = value;
					this.SendPropertyChanged("EMP_TITLE");
					this.OnEMP_TITLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_LNAME", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string EMP_LNAME
		{
			get
			{
				return this._EMP_LNAME;
			}
			set
			{
				if ((this._EMP_LNAME != value))
				{
					this.OnEMP_LNAMEChanging(value);
					this.SendPropertyChanging();
					this._EMP_LNAME = value;
					this.SendPropertyChanged("EMP_LNAME");
					this.OnEMP_LNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_FNAME", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string EMP_FNAME
		{
			get
			{
				return this._EMP_FNAME;
			}
			set
			{
				if ((this._EMP_FNAME != value))
				{
					this.OnEMP_FNAMEChanging(value);
					this.SendPropertyChanging();
					this._EMP_FNAME = value;
					this.SendPropertyChanged("EMP_FNAME");
					this.OnEMP_FNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_INITIAL", DbType="Char(1)")]
		public System.Nullable<char> EMP_INITIAL
		{
			get
			{
				return this._EMP_INITIAL;
			}
			set
			{
				if ((this._EMP_INITIAL != value))
				{
					this.OnEMP_INITIALChanging(value);
					this.SendPropertyChanging();
					this._EMP_INITIAL = value;
					this.SendPropertyChanged("EMP_INITIAL");
					this.OnEMP_INITIALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_DOB", DbType="Date")]
		public System.Nullable<System.DateTime> EMP_DOB
		{
			get
			{
				return this._EMP_DOB;
			}
			set
			{
				if ((this._EMP_DOB != value))
				{
					this.OnEMP_DOBChanging(value);
					this.SendPropertyChanging();
					this._EMP_DOB = value;
					this.SendPropertyChanged("EMP_DOB");
					this.OnEMP_DOBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_HIRE_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> EMP_HIRE_DATE
		{
			get
			{
				return this._EMP_HIRE_DATE;
			}
			set
			{
				if ((this._EMP_HIRE_DATE != value))
				{
					this.OnEMP_HIRE_DATEChanging(value);
					this.SendPropertyChanging();
					this._EMP_HIRE_DATE = value;
					this.SendPropertyChanged("EMP_HIRE_DATE");
					this.OnEMP_HIRE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_YEARS", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> EMP_YEARS
		{
			get
			{
				return this._EMP_YEARS;
			}
			set
			{
				if ((this._EMP_YEARS != value))
				{
					this.OnEMP_YEARSChanging(value);
					this.SendPropertyChanging();
					this._EMP_YEARS = value;
					this.SendPropertyChanged("EMP_YEARS");
					this.OnEMP_YEARSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_AREACODE", DbType="Char(3)")]
		public string EMP_AREACODE
		{
			get
			{
				return this._EMP_AREACODE;
			}
			set
			{
				if ((this._EMP_AREACODE != value))
				{
					this.OnEMP_AREACODEChanging(value);
					this.SendPropertyChanging();
					this._EMP_AREACODE = value;
					this.SendPropertyChanged("EMP_AREACODE");
					this.OnEMP_AREACODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_PHONE", DbType="Char(8)")]
		public string EMP_PHONE
		{
			get
			{
				return this._EMP_PHONE;
			}
			set
			{
				if ((this._EMP_PHONE != value))
				{
					this.OnEMP_PHONEChanging(value);
					this.SendPropertyChanging();
					this._EMP_PHONE = value;
					this.SendPropertyChanged("EMP_PHONE");
					this.OnEMP_PHONEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.INVOICE")]
	public partial class INVOICE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _INV_NUMBER;
		
		private decimal _CUS_CODE;
		
		private System.DateTime _INV_DATE;
		
		private EntitySet<LINE> _LINEs;
		
		private EntityRef<CUSTOMER> _CUSTOMER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnINV_NUMBERChanging(decimal value);
    partial void OnINV_NUMBERChanged();
    partial void OnCUS_CODEChanging(decimal value);
    partial void OnCUS_CODEChanged();
    partial void OnINV_DATEChanging(System.DateTime value);
    partial void OnINV_DATEChanged();
    #endregion
		
		public INVOICE()
		{
			this._LINEs = new EntitySet<LINE>(new Action<LINE>(this.attach_LINEs), new Action<LINE>(this.detach_LINEs));
			this._CUSTOMER = default(EntityRef<CUSTOMER>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INV_NUMBER", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal INV_NUMBER
		{
			get
			{
				return this._INV_NUMBER;
			}
			set
			{
				if ((this._INV_NUMBER != value))
				{
					this.OnINV_NUMBERChanging(value);
					this.SendPropertyChanging();
					this._INV_NUMBER = value;
					this.SendPropertyChanged("INV_NUMBER");
					this.OnINV_NUMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUS_CODE", DbType="Decimal(18,0) NOT NULL")]
		public decimal CUS_CODE
		{
			get
			{
				return this._CUS_CODE;
			}
			set
			{
				if ((this._CUS_CODE != value))
				{
					if (this._CUSTOMER.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCUS_CODEChanging(value);
					this.SendPropertyChanging();
					this._CUS_CODE = value;
					this.SendPropertyChanged("CUS_CODE");
					this.OnCUS_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INV_DATE", DbType="Date NOT NULL")]
		public System.DateTime INV_DATE
		{
			get
			{
				return this._INV_DATE;
			}
			set
			{
				if ((this._INV_DATE != value))
				{
					this.OnINV_DATEChanging(value);
					this.SendPropertyChanging();
					this._INV_DATE = value;
					this.SendPropertyChanged("INV_DATE");
					this.OnINV_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="INVOICE_LINE", Storage="_LINEs", ThisKey="INV_NUMBER", OtherKey="INV_NUMBER")]
		public EntitySet<LINE> LINEs
		{
			get
			{
				return this._LINEs;
			}
			set
			{
				this._LINEs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CUSTOMER_INVOICE", Storage="_CUSTOMER", ThisKey="CUS_CODE", OtherKey="CUS_CODE", IsForeignKey=true)]
		public CUSTOMER CUSTOMER
		{
			get
			{
				return this._CUSTOMER.Entity;
			}
			set
			{
				CUSTOMER previousValue = this._CUSTOMER.Entity;
				if (((previousValue != value) 
							|| (this._CUSTOMER.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CUSTOMER.Entity = null;
						previousValue.INVOICEs.Remove(this);
					}
					this._CUSTOMER.Entity = value;
					if ((value != null))
					{
						value.INVOICEs.Add(this);
						this._CUS_CODE = value.CUS_CODE;
					}
					else
					{
						this._CUS_CODE = default(decimal);
					}
					this.SendPropertyChanged("CUSTOMER");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LINEs(LINE entity)
		{
			this.SendPropertyChanging();
			entity.INVOICE = this;
		}
		
		private void detach_LINEs(LINE entity)
		{
			this.SendPropertyChanging();
			entity.INVOICE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LINE")]
	public partial class LINE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _INV_NUMBER;
		
		private decimal _LINE_NUMBER;
		
		private string _P_CODE;
		
		private decimal _LINE_UNITS;
		
		private decimal _LINE_PRICE;
		
		private EntityRef<INVOICE> _INVOICE;
		
		private EntityRef<PRODUCT> _PRODUCT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnINV_NUMBERChanging(decimal value);
    partial void OnINV_NUMBERChanged();
    partial void OnLINE_NUMBERChanging(decimal value);
    partial void OnLINE_NUMBERChanged();
    partial void OnP_CODEChanging(string value);
    partial void OnP_CODEChanged();
    partial void OnLINE_UNITSChanging(decimal value);
    partial void OnLINE_UNITSChanged();
    partial void OnLINE_PRICEChanging(decimal value);
    partial void OnLINE_PRICEChanged();
    #endregion
		
		public LINE()
		{
			this._INVOICE = default(EntityRef<INVOICE>);
			this._PRODUCT = default(EntityRef<PRODUCT>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INV_NUMBER", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal INV_NUMBER
		{
			get
			{
				return this._INV_NUMBER;
			}
			set
			{
				if ((this._INV_NUMBER != value))
				{
					if (this._INVOICE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnINV_NUMBERChanging(value);
					this.SendPropertyChanging();
					this._INV_NUMBER = value;
					this.SendPropertyChanged("INV_NUMBER");
					this.OnINV_NUMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LINE_NUMBER", DbType="Decimal(2,0) NOT NULL", IsPrimaryKey=true)]
		public decimal LINE_NUMBER
		{
			get
			{
				return this._LINE_NUMBER;
			}
			set
			{
				if ((this._LINE_NUMBER != value))
				{
					this.OnLINE_NUMBERChanging(value);
					this.SendPropertyChanging();
					this._LINE_NUMBER = value;
					this.SendPropertyChanged("LINE_NUMBER");
					this.OnLINE_NUMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_CODE", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string P_CODE
		{
			get
			{
				return this._P_CODE;
			}
			set
			{
				if ((this._P_CODE != value))
				{
					if (this._PRODUCT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnP_CODEChanging(value);
					this.SendPropertyChanging();
					this._P_CODE = value;
					this.SendPropertyChanged("P_CODE");
					this.OnP_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LINE_UNITS", DbType="Decimal(9,2) NOT NULL")]
		public decimal LINE_UNITS
		{
			get
			{
				return this._LINE_UNITS;
			}
			set
			{
				if ((this._LINE_UNITS != value))
				{
					this.OnLINE_UNITSChanging(value);
					this.SendPropertyChanging();
					this._LINE_UNITS = value;
					this.SendPropertyChanged("LINE_UNITS");
					this.OnLINE_UNITSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LINE_PRICE", DbType="Decimal(9,2) NOT NULL")]
		public decimal LINE_PRICE
		{
			get
			{
				return this._LINE_PRICE;
			}
			set
			{
				if ((this._LINE_PRICE != value))
				{
					this.OnLINE_PRICEChanging(value);
					this.SendPropertyChanging();
					this._LINE_PRICE = value;
					this.SendPropertyChanged("LINE_PRICE");
					this.OnLINE_PRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="INVOICE_LINE", Storage="_INVOICE", ThisKey="INV_NUMBER", OtherKey="INV_NUMBER", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public INVOICE INVOICE
		{
			get
			{
				return this._INVOICE.Entity;
			}
			set
			{
				INVOICE previousValue = this._INVOICE.Entity;
				if (((previousValue != value) 
							|| (this._INVOICE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._INVOICE.Entity = null;
						previousValue.LINEs.Remove(this);
					}
					this._INVOICE.Entity = value;
					if ((value != null))
					{
						value.LINEs.Add(this);
						this._INV_NUMBER = value.INV_NUMBER;
					}
					else
					{
						this._INV_NUMBER = default(decimal);
					}
					this.SendPropertyChanged("INVOICE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PRODUCT_LINE", Storage="_PRODUCT", ThisKey="P_CODE", OtherKey="P_CODE", IsForeignKey=true)]
		public PRODUCT PRODUCT
		{
			get
			{
				return this._PRODUCT.Entity;
			}
			set
			{
				PRODUCT previousValue = this._PRODUCT.Entity;
				if (((previousValue != value) 
							|| (this._PRODUCT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PRODUCT.Entity = null;
						previousValue.LINEs.Remove(this);
					}
					this._PRODUCT.Entity = value;
					if ((value != null))
					{
						value.LINEs.Add(this);
						this._P_CODE = value.P_CODE;
					}
					else
					{
						this._P_CODE = default(string);
					}
					this.SendPropertyChanged("PRODUCT");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.P")]
	public partial class P : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _P_CODE;
		
		private string _P_DESCRIPT;
		
		private System.DateTime _P_INDATE;
		
		private decimal _P_QOH;
		
		private decimal _P_MIN;
		
		private decimal _P_PRICE;
		
		private decimal _P_DISCOUNT;
		
		private System.Nullable<decimal> _V_CODE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnP_CODEChanging(string value);
    partial void OnP_CODEChanged();
    partial void OnP_DESCRIPTChanging(string value);
    partial void OnP_DESCRIPTChanged();
    partial void OnP_INDATEChanging(System.DateTime value);
    partial void OnP_INDATEChanged();
    partial void OnP_QOHChanging(decimal value);
    partial void OnP_QOHChanged();
    partial void OnP_MINChanging(decimal value);
    partial void OnP_MINChanged();
    partial void OnP_PRICEChanging(decimal value);
    partial void OnP_PRICEChanged();
    partial void OnP_DISCOUNTChanging(decimal value);
    partial void OnP_DISCOUNTChanged();
    partial void OnV_CODEChanging(System.Nullable<decimal> value);
    partial void OnV_CODEChanged();
    #endregion
		
		public P()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_CODE", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string P_CODE
		{
			get
			{
				return this._P_CODE;
			}
			set
			{
				if ((this._P_CODE != value))
				{
					this.OnP_CODEChanging(value);
					this.SendPropertyChanging();
					this._P_CODE = value;
					this.SendPropertyChanged("P_CODE");
					this.OnP_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_DESCRIPT", DbType="VarChar(35) NOT NULL", CanBeNull=false)]
		public string P_DESCRIPT
		{
			get
			{
				return this._P_DESCRIPT;
			}
			set
			{
				if ((this._P_DESCRIPT != value))
				{
					this.OnP_DESCRIPTChanging(value);
					this.SendPropertyChanging();
					this._P_DESCRIPT = value;
					this.SendPropertyChanged("P_DESCRIPT");
					this.OnP_DESCRIPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_INDATE", DbType="Date NOT NULL")]
		public System.DateTime P_INDATE
		{
			get
			{
				return this._P_INDATE;
			}
			set
			{
				if ((this._P_INDATE != value))
				{
					this.OnP_INDATEChanging(value);
					this.SendPropertyChanging();
					this._P_INDATE = value;
					this.SendPropertyChanged("P_INDATE");
					this.OnP_INDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_QOH", DbType="Decimal(18,0) NOT NULL")]
		public decimal P_QOH
		{
			get
			{
				return this._P_QOH;
			}
			set
			{
				if ((this._P_QOH != value))
				{
					this.OnP_QOHChanging(value);
					this.SendPropertyChanging();
					this._P_QOH = value;
					this.SendPropertyChanged("P_QOH");
					this.OnP_QOHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_MIN", DbType="Decimal(18,0) NOT NULL")]
		public decimal P_MIN
		{
			get
			{
				return this._P_MIN;
			}
			set
			{
				if ((this._P_MIN != value))
				{
					this.OnP_MINChanging(value);
					this.SendPropertyChanging();
					this._P_MIN = value;
					this.SendPropertyChanged("P_MIN");
					this.OnP_MINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_PRICE", DbType="Decimal(8,2) NOT NULL")]
		public decimal P_PRICE
		{
			get
			{
				return this._P_PRICE;
			}
			set
			{
				if ((this._P_PRICE != value))
				{
					this.OnP_PRICEChanging(value);
					this.SendPropertyChanging();
					this._P_PRICE = value;
					this.SendPropertyChanged("P_PRICE");
					this.OnP_PRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_DISCOUNT", DbType="Decimal(5,2) NOT NULL")]
		public decimal P_DISCOUNT
		{
			get
			{
				return this._P_DISCOUNT;
			}
			set
			{
				if ((this._P_DISCOUNT != value))
				{
					this.OnP_DISCOUNTChanging(value);
					this.SendPropertyChanging();
					this._P_DISCOUNT = value;
					this.SendPropertyChanged("P_DISCOUNT");
					this.OnP_DISCOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_V_CODE", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> V_CODE
		{
			get
			{
				return this._V_CODE;
			}
			set
			{
				if ((this._V_CODE != value))
				{
					this.OnV_CODEChanging(value);
					this.SendPropertyChanging();
					this._V_CODE = value;
					this.SendPropertyChanged("V_CODE");
					this.OnV_CODEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PRODUCT")]
	public partial class PRODUCT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _P_CODE;
		
		private string _P_DESCRIPT;
		
		private System.DateTime _P_INDATE;
		
		private decimal _P_QOH;
		
		private decimal _P_MIN;
		
		private decimal _P_PRICE;
		
		private decimal _P_DISCOUNT;
		
		private System.Nullable<int> _V_CODE;
		
		private EntitySet<LINE> _LINEs;
		
		private EntityRef<VENDOR> _VENDOR;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnP_CODEChanging(string value);
    partial void OnP_CODEChanged();
    partial void OnP_DESCRIPTChanging(string value);
    partial void OnP_DESCRIPTChanged();
    partial void OnP_INDATEChanging(System.DateTime value);
    partial void OnP_INDATEChanged();
    partial void OnP_QOHChanging(decimal value);
    partial void OnP_QOHChanged();
    partial void OnP_MINChanging(decimal value);
    partial void OnP_MINChanged();
    partial void OnP_PRICEChanging(decimal value);
    partial void OnP_PRICEChanged();
    partial void OnP_DISCOUNTChanging(decimal value);
    partial void OnP_DISCOUNTChanged();
    partial void OnV_CODEChanging(System.Nullable<int> value);
    partial void OnV_CODEChanged();
    #endregion
		
		public PRODUCT()
		{
			this._LINEs = new EntitySet<LINE>(new Action<LINE>(this.attach_LINEs), new Action<LINE>(this.detach_LINEs));
			this._VENDOR = default(EntityRef<VENDOR>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_CODE", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string P_CODE
		{
			get
			{
				return this._P_CODE;
			}
			set
			{
				if ((this._P_CODE != value))
				{
					this.OnP_CODEChanging(value);
					this.SendPropertyChanging();
					this._P_CODE = value;
					this.SendPropertyChanged("P_CODE");
					this.OnP_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_DESCRIPT", DbType="VarChar(35) NOT NULL", CanBeNull=false)]
		public string P_DESCRIPT
		{
			get
			{
				return this._P_DESCRIPT;
			}
			set
			{
				if ((this._P_DESCRIPT != value))
				{
					this.OnP_DESCRIPTChanging(value);
					this.SendPropertyChanging();
					this._P_DESCRIPT = value;
					this.SendPropertyChanged("P_DESCRIPT");
					this.OnP_DESCRIPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_INDATE", DbType="Date NOT NULL")]
		public System.DateTime P_INDATE
		{
			get
			{
				return this._P_INDATE;
			}
			set
			{
				if ((this._P_INDATE != value))
				{
					this.OnP_INDATEChanging(value);
					this.SendPropertyChanging();
					this._P_INDATE = value;
					this.SendPropertyChanged("P_INDATE");
					this.OnP_INDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_QOH", DbType="Decimal(18,0) NOT NULL")]
		public decimal P_QOH
		{
			get
			{
				return this._P_QOH;
			}
			set
			{
				if ((this._P_QOH != value))
				{
					this.OnP_QOHChanging(value);
					this.SendPropertyChanging();
					this._P_QOH = value;
					this.SendPropertyChanged("P_QOH");
					this.OnP_QOHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_MIN", DbType="Decimal(18,0) NOT NULL")]
		public decimal P_MIN
		{
			get
			{
				return this._P_MIN;
			}
			set
			{
				if ((this._P_MIN != value))
				{
					this.OnP_MINChanging(value);
					this.SendPropertyChanging();
					this._P_MIN = value;
					this.SendPropertyChanged("P_MIN");
					this.OnP_MINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_PRICE", DbType="Decimal(8,2) NOT NULL")]
		public decimal P_PRICE
		{
			get
			{
				return this._P_PRICE;
			}
			set
			{
				if ((this._P_PRICE != value))
				{
					this.OnP_PRICEChanging(value);
					this.SendPropertyChanging();
					this._P_PRICE = value;
					this.SendPropertyChanged("P_PRICE");
					this.OnP_PRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_DISCOUNT", DbType="Decimal(5,2) NOT NULL")]
		public decimal P_DISCOUNT
		{
			get
			{
				return this._P_DISCOUNT;
			}
			set
			{
				if ((this._P_DISCOUNT != value))
				{
					this.OnP_DISCOUNTChanging(value);
					this.SendPropertyChanging();
					this._P_DISCOUNT = value;
					this.SendPropertyChanged("P_DISCOUNT");
					this.OnP_DISCOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_V_CODE", DbType="Int")]
		public System.Nullable<int> V_CODE
		{
			get
			{
				return this._V_CODE;
			}
			set
			{
				if ((this._V_CODE != value))
				{
					if (this._VENDOR.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnV_CODEChanging(value);
					this.SendPropertyChanging();
					this._V_CODE = value;
					this.SendPropertyChanged("V_CODE");
					this.OnV_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PRODUCT_LINE", Storage="_LINEs", ThisKey="P_CODE", OtherKey="P_CODE")]
		public EntitySet<LINE> LINEs
		{
			get
			{
				return this._LINEs;
			}
			set
			{
				this._LINEs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VENDOR_PRODUCT", Storage="_VENDOR", ThisKey="V_CODE", OtherKey="V_CODE", IsForeignKey=true)]
		public VENDOR VENDOR
		{
			get
			{
				return this._VENDOR.Entity;
			}
			set
			{
				VENDOR previousValue = this._VENDOR.Entity;
				if (((previousValue != value) 
							|| (this._VENDOR.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._VENDOR.Entity = null;
						previousValue.PRODUCTs.Remove(this);
					}
					this._VENDOR.Entity = value;
					if ((value != null))
					{
						value.PRODUCTs.Add(this);
						this._V_CODE = value.V_CODE;
					}
					else
					{
						this._V_CODE = default(Nullable<int>);
					}
					this.SendPropertyChanged("VENDOR");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LINEs(LINE entity)
		{
			this.SendPropertyChanging();
			entity.PRODUCT = this;
		}
		
		private void detach_LINEs(LINE entity)
		{
			this.SendPropertyChanging();
			entity.PRODUCT = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V")]
	public partial class V : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _V_CODE;
		
		private string _V_NAME;
		
		private string _V_CONTACT;
		
		private string _V_AREACODE;
		
		private string _V_PHONE;
		
		private string _V_STATE;
		
		private char _V_ORDER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnV_CODEChanging(int value);
    partial void OnV_CODEChanged();
    partial void OnV_NAMEChanging(string value);
    partial void OnV_NAMEChanged();
    partial void OnV_CONTACTChanging(string value);
    partial void OnV_CONTACTChanged();
    partial void OnV_AREACODEChanging(string value);
    partial void OnV_AREACODEChanged();
    partial void OnV_PHONEChanging(string value);
    partial void OnV_PHONEChanged();
    partial void OnV_STATEChanging(string value);
    partial void OnV_STATEChanged();
    partial void OnV_ORDERChanging(char value);
    partial void OnV_ORDERChanged();
    #endregion
		
		public V()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_V_CODE", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int V_CODE
		{
			get
			{
				return this._V_CODE;
			}
			set
			{
				if ((this._V_CODE != value))
				{
					this.OnV_CODEChanging(value);
					this.SendPropertyChanging();
					this._V_CODE = value;
					this.SendPropertyChanged("V_CODE");
					this.OnV_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_V_NAME", DbType="VarChar(35) NOT NULL", CanBeNull=false)]
		public string V_NAME
		{
			get
			{
				return this._V_NAME;
			}
			set
			{
				if ((this._V_NAME != value))
				{
					this.OnV_NAMEChanging(value);
					this.SendPropertyChanging();
					this._V_NAME = value;
					this.SendPropertyChanged("V_NAME");
					this.OnV_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_V_CONTACT", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string V_CONTACT
		{
			get
			{
				return this._V_CONTACT;
			}
			set
			{
				if ((this._V_CONTACT != value))
				{
					this.OnV_CONTACTChanging(value);
					this.SendPropertyChanging();
					this._V_CONTACT = value;
					this.SendPropertyChanged("V_CONTACT");
					this.OnV_CONTACTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_V_AREACODE", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string V_AREACODE
		{
			get
			{
				return this._V_AREACODE;
			}
			set
			{
				if ((this._V_AREACODE != value))
				{
					this.OnV_AREACODEChanging(value);
					this.SendPropertyChanging();
					this._V_AREACODE = value;
					this.SendPropertyChanged("V_AREACODE");
					this.OnV_AREACODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_V_PHONE", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string V_PHONE
		{
			get
			{
				return this._V_PHONE;
			}
			set
			{
				if ((this._V_PHONE != value))
				{
					this.OnV_PHONEChanging(value);
					this.SendPropertyChanging();
					this._V_PHONE = value;
					this.SendPropertyChanged("V_PHONE");
					this.OnV_PHONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_V_STATE", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string V_STATE
		{
			get
			{
				return this._V_STATE;
			}
			set
			{
				if ((this._V_STATE != value))
				{
					this.OnV_STATEChanging(value);
					this.SendPropertyChanging();
					this._V_STATE = value;
					this.SendPropertyChanged("V_STATE");
					this.OnV_STATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_V_ORDER", DbType="Char(1) NOT NULL")]
		public char V_ORDER
		{
			get
			{
				return this._V_ORDER;
			}
			set
			{
				if ((this._V_ORDER != value))
				{
					this.OnV_ORDERChanging(value);
					this.SendPropertyChanging();
					this._V_ORDER = value;
					this.SendPropertyChanged("V_ORDER");
					this.OnV_ORDERChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VENDOR")]
	public partial class VENDOR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _V_CODE;
		
		private string _V_NAME;
		
		private string _V_CONTACT;
		
		private string _V_AREACODE;
		
		private string _V_PHONE;
		
		private string _V_STATE;
		
		private char _V_ORDER;
		
		private EntitySet<PRODUCT> _PRODUCTs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnV_CODEChanging(int value);
    partial void OnV_CODEChanged();
    partial void OnV_NAMEChanging(string value);
    partial void OnV_NAMEChanged();
    partial void OnV_CONTACTChanging(string value);
    partial void OnV_CONTACTChanged();
    partial void OnV_AREACODEChanging(string value);
    partial void OnV_AREACODEChanged();
    partial void OnV_PHONEChanging(string value);
    partial void OnV_PHONEChanged();
    partial void OnV_STATEChanging(string value);
    partial void OnV_STATEChanged();
    partial void OnV_ORDERChanging(char value);
    partial void OnV_ORDERChanged();
    #endregion
		
		public VENDOR()
		{
			this._PRODUCTs = new EntitySet<PRODUCT>(new Action<PRODUCT>(this.attach_PRODUCTs), new Action<PRODUCT>(this.detach_PRODUCTs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_V_CODE", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int V_CODE
		{
			get
			{
				return this._V_CODE;
			}
			set
			{
				if ((this._V_CODE != value))
				{
					this.OnV_CODEChanging(value);
					this.SendPropertyChanging();
					this._V_CODE = value;
					this.SendPropertyChanged("V_CODE");
					this.OnV_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_V_NAME", DbType="VarChar(35) NOT NULL", CanBeNull=false)]
		public string V_NAME
		{
			get
			{
				return this._V_NAME;
			}
			set
			{
				if ((this._V_NAME != value))
				{
					this.OnV_NAMEChanging(value);
					this.SendPropertyChanging();
					this._V_NAME = value;
					this.SendPropertyChanged("V_NAME");
					this.OnV_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_V_CONTACT", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string V_CONTACT
		{
			get
			{
				return this._V_CONTACT;
			}
			set
			{
				if ((this._V_CONTACT != value))
				{
					this.OnV_CONTACTChanging(value);
					this.SendPropertyChanging();
					this._V_CONTACT = value;
					this.SendPropertyChanged("V_CONTACT");
					this.OnV_CONTACTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_V_AREACODE", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string V_AREACODE
		{
			get
			{
				return this._V_AREACODE;
			}
			set
			{
				if ((this._V_AREACODE != value))
				{
					this.OnV_AREACODEChanging(value);
					this.SendPropertyChanging();
					this._V_AREACODE = value;
					this.SendPropertyChanged("V_AREACODE");
					this.OnV_AREACODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_V_PHONE", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string V_PHONE
		{
			get
			{
				return this._V_PHONE;
			}
			set
			{
				if ((this._V_PHONE != value))
				{
					this.OnV_PHONEChanging(value);
					this.SendPropertyChanging();
					this._V_PHONE = value;
					this.SendPropertyChanged("V_PHONE");
					this.OnV_PHONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_V_STATE", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string V_STATE
		{
			get
			{
				return this._V_STATE;
			}
			set
			{
				if ((this._V_STATE != value))
				{
					this.OnV_STATEChanging(value);
					this.SendPropertyChanging();
					this._V_STATE = value;
					this.SendPropertyChanged("V_STATE");
					this.OnV_STATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_V_ORDER", DbType="Char(1) NOT NULL")]
		public char V_ORDER
		{
			get
			{
				return this._V_ORDER;
			}
			set
			{
				if ((this._V_ORDER != value))
				{
					this.OnV_ORDERChanging(value);
					this.SendPropertyChanging();
					this._V_ORDER = value;
					this.SendPropertyChanged("V_ORDER");
					this.OnV_ORDERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VENDOR_PRODUCT", Storage="_PRODUCTs", ThisKey="V_CODE", OtherKey="V_CODE")]
		public EntitySet<PRODUCT> PRODUCTs
		{
			get
			{
				return this._PRODUCTs;
			}
			set
			{
				this._PRODUCTs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PRODUCTs(PRODUCT entity)
		{
			this.SendPropertyChanging();
			entity.VENDOR = this;
		}
		
		private void detach_PRODUCTs(PRODUCT entity)
		{
			this.SendPropertyChanging();
			entity.VENDOR = null;
		}
	}
}
#pragma warning restore 1591
